const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(){
 const storage=new Map(),save={set:{},cash:0,xp:0,lvl:1};
 const ctx={console:{log(){},warn(){},error(){}},crypto:globalThis.crypto,AbortController,Response,fetch:async()=>new Response('{}'),setTimeout:(f,ms)=>setTimeout(f,Math.min(ms,50)),clearTimeout,setInterval,clearInterval,location:{protocol:'file:'},document:{head:{insertAdjacentHTML(){}},hidden:false},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},S:()=>save,UI:{refresh(){},toast(){}},Object,JSON,Number,Date};
 ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/net.js'),'utf8'),ctx);const net=ctx.OGRA_NET;net.token=async()=>'test-token';net.user={id:'test-user'};net.gate=()=>{};net.online=true;net.practice=false;net.protocol=2;return{ctx,net,save,storage};
}
test('empty sync is GET and contains no preference-overwriting body',async()=>{const{ctx,net}=setup();let req;ctx.fetch=async(url,r)=>{req=r;return new Response('{"ok":true}')} ;await net.call('sync',{local:{}});assert.equal(req.method,'GET');assert.equal(req.body,undefined)});
test('network timeout returns without locking the UI',async()=>{const{ctx,net}=setup();ctx.fetch=(url,r)=>new Promise((resolve,reject)=>r.signal.addEventListener('abort',()=>reject(new Error('aborted'))));const t=Date.now();assert.equal(await net.call('purchase',{}),null);assert.ok(Date.now()-t<500)});
test('failed profile response cannot turn online mode on',async()=>{const{net}=setup();net.online=false;net.call=async()=>({error:'bad session'});net.offline=()=>{net.practice=true};await net.loadProfile();assert.equal(net.online,false);assert.equal(net.practice,true)});
test('older snapshots cannot overwrite a newer server balance',()=>{const{net,save}=setup();net.adopt({cash:100,xp:10,level:2,revision:5});net.adopt({cash:1,xp:0,level:1,revision:4});assert.equal(save.cash,100);assert.equal(save.lvl,2)});
test('uncertain purchase retry reuses the same request receipt',async()=>{const{net}=setup();const ids=[];let attempts=0;net.call=async(name,body)=>{if(name==='sync')return null;ids.push(body.requestId);return ++attempts===1?null:{ok:true,cash:100,revision:2}};await net.buy('daily',{});await net.buy('daily',{});assert.equal(ids.length,2);assert.equal(ids[0],ids[1])});
test('overlapping purchase is refused while first is pending',async()=>{const{net}=setup();let done;net.call=()=>new Promise(r=>done=r);const a=net.buy('daily',{});const b=await net.buy('daily',{});assert.ok(b.error.includes('already'));done(null);await a;assert.equal(net._buying,false)});
test('trip pending receipt survives a network failure and clears on confirmation',async()=>{const{net,storage}=setup();net.call=async()=>null;await net.reportTrip({runPromise:Promise.resolve({ok:true,runId:crypto.randomUUID()}),distanceKm:1});assert.equal(storage.size,1);net.call=async()=>({ok:true});await net.retryTrip();assert.equal(storage.size,0)});
